name: 'Bind Deploy Action'
description: 'Action to generate serial numbers and deploy zones to BIND servers'
author: 'Mitchell'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: truck
  color: green